[package]
name = "verilog-parser"
version = "0.1.0"
edition = "2021"
exclude = ["build"]
rust-version = "1.66"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 使用Pest解析器生成器库的依赖项
[dependencies]
pest = "2.6"
pest_derive = "2.6"

# 配置build选项
[profile.dev]
debug = true
